auth0:
  audience: https://dev-uut3mgn6yn6odyvb.us.auth0.com/api/v2/
spring:
  sendgrid:
    api-key: ${apiSedGrip}
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${client-id-auth0}
            client-secret: ${client-scret-aut0}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: ${issuer-uri-aut0}
      resource-server:
        jwt:
          issuer-uri: ${issuer-uri-jwt-auth0}

  cloud:
    azure:
      keyvault:
        secret:
          property-sources-enable: true
          property-sources[0]:
            endpoint: https://publiucokey.vault.azure.net/

  datasource:
    url: ${datasource-url}
    username: ${data-username}
    password: ${data-password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
email: fede.zapata16@gmail.com
email-receiver: federico.zapata4970@soyuco.edu.co
